# Nombre de la app
spring.application.name=brightsmile-backend

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/brightsmile
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto
server.port=8080

# Data SQL
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always


# OpenAI
openai.api.key=TU_API_KEY_AQUI
openai.api.url=https://api.openai.com/v1/chat/completions
openai.model=gpt-4o-mini



